<?xml version="1.0" encoding="UTF-8"?>
<!--Generated by fashionquadrant S-Aggregator version 1.1.3 @ http://www.afashionquadrant.com/saggregator/ for more information.-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fashionquadrant="http://www.afashionquadrant.com" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="#all">
  <xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
  <xsl:variable name="XML" select="/"/>
  <xsl:template match="/">
    <xsl:call-template name="fashionquadrant:Root"/>
  </xsl:template>
  <xsl:template name="fashionquadrant:Root">
    <html>
      <head>
        <meta name="generator" content="fashionquadrant S-Aggregator version 1.1.3"/>
        <meta http-equiv="X-UA-Compatible" content="IE=6"/>
        <style type="text/css">
          <xsl:comment>@import  url("/styles/eagletheme4.css");</xsl:comment>
        </style>
      </head>
      <body class="xmainbg">
        <xsl:for-each select="$XML">
          <xsl:for-each select="catalog">
            <div class="xadvertbg">
              <xsl:for-each select="advertcatalog">
                <xsl:for-each select="advert">

                  <div class="atitle">
                    <xsl:for-each select="title">
                      <xsl:apply-templates/>
                    </xsl:for-each>
                  </div>
                  <div class="aheaderad">
                    <xsl:for-each select="headerad">
                      <xsl:apply-templates/>
                    </xsl:for-each>
                  </div>
                  <div class="adescription">
                    <xsl:for-each select="shortdescription">
                      <xsl:apply-templates/>
                    </xsl:for-each>
                  </div>
                  <a class="alink">
                    <xsl:attribute name="target">
                      <xsl:text>_blank</xsl:text>
                    </xsl:attribute>
                    <xsl:choose>
                      <xsl:when test="not(string(hlink))">
                        <xsl:attribute name="href">
                          <xsl:text>#</xsl:text>
                        </xsl:attribute>
                      </xsl:when>
                      <xsl:when test="substring(string(hlink), 1, 1) = '#'">
                        <xsl:attribute name="href">
                          <xsl:value-of select="hlink"/>
                        </xsl:attribute>
                      </xsl:when>
                      <xsl:otherwise>
                        <xsl:attribute name="href">
                          <xsl:if test="substring(string(hlink), 2, 1) = ':'">
                            <xsl:text>file:///</xsl:text>
                          </xsl:if>
                          <xsl:value-of select="translate(string(hlink), '&#x5c;', '/')"/>
                        </xsl:attribute>
                      </xsl:otherwise>
                    </xsl:choose>
                    Goto Advert >>
                  </a>
                </xsl:for-each>
              </xsl:for-each>
            </div>
            <div class="xbodybg">
              <xsl:for-each select="jobcatalog">
                <xsl:for-each select="job">

                  <div class="ftitle">
                    <xsl:for-each select="title">
                      <xsl:apply-templates/>
                    </xsl:for-each>
                  </div>
                  <div class="fdate">
                    <xsl:for-each select="posteddate">
                      <xsl:apply-templates/>
                    </xsl:for-each>
                  </div>
                  <div class="fdescription">
                    <xsl:for-each select="shortdescription">
                      <xsl:apply-templates/>
                    </xsl:for-each>
                  </div>
                  <a class="flink">
                    <xsl:attribute name="target">
                      <xsl:text>_blank</xsl:text>
                    </xsl:attribute>
                    <xsl:choose>
                      <xsl:when test="not(string(hlink))">
                        <xsl:attribute name="href">
                          <xsl:text>#</xsl:text>
                        </xsl:attribute>
                      </xsl:when>
                      <xsl:when test="substring(string(hlink), 1, 1) = '#'">
                        <xsl:attribute name="href">
                          <xsl:value-of select="hlink"/>
                        </xsl:attribute>
                      </xsl:when>
                      <xsl:otherwise>
                        <xsl:attribute name="href">
                          <xsl:if test="substring(string(hlink), 2, 1) = ':'">
                            <xsl:text>file:///</xsl:text>
                          </xsl:if>
                          <xsl:value-of select="translate(string(hlink), '&#x5c;', '/')"/>
                        </xsl:attribute>
                      </xsl:otherwise>
                    </xsl:choose>
                    Apply >>
                  </a>
                  <div class="abreak"></div>
                </xsl:for-each>
              </xsl:for-each>
            </div>
          </xsl:for-each>
        </xsl:for-each>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>